GET http://localhost:3000/api/auth/login

###

POST http://localhost:3000/api/auth/login 
Content-Type: application/json

{
    "email": "g@g",
    "pwd": "g"
}

###
GET http://localhost:3000/api/articles/1?auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYyMjE0MjUzNn0.PTh6SH-vlqCtEuLBAvFHWtomb_8TpxXwsRMbSWPE2h4

###
POST http://localhost:3000/api/carts/1/articles?auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYyMjE0MjUzNn0.PTh6SH-vlqCtEuLBAvFHWtomb_8TpxXwsRMbSWPE2h4
Content-Type: application/json

{
    "artId":1
}

###
POST http://localhost:3000/api/carts/1/articles?auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYyMjE0MjUzNn0.PTh6SH-vlqCtEuLBAvFHWtomb_8TpxXwsRMbSWPE2h4
Content-Type: application/json

{
    "artId":2
}
###
POST http://localhost:3000/api/carts/1/articles?auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYyMjE0MjUzNn0.PTh6SH-vlqCtEuLBAvFHWtomb_8TpxXwsRMbSWPE2h4
Content-Type: application/json

{
    "artId":1
}
###
PUT http://localhost:3000/api/carts/1/articles/1?auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYyMjE0MjUzNn0.PTh6SH-vlqCtEuLBAvFHWtomb_8TpxXwsRMbSWPE2h4


###
DELETE http://localhost:3000/api/carts/1/articles/1?auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYyMjE0MjUzNn0.PTh6SH-vlqCtEuLBAvFHWtomb_8TpxXwsRMbSWPE2h4

###
DELETE http://localhost:3000/api/carts/1/articles?auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYyMjE0MjUzNn0.PTh6SH-vlqCtEuLBAvFHWtomb_8TpxXwsRMbSWPE2h4

###
GET http://localhost:3000/api/carts/1/articles/1?auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYyMjE0MjUzNn0.PTh6SH-vlqCtEuLBAvFHWtomb_8TpxXwsRMbSWPE2h4

###
GET http://localhost:3000/api/carts/1/articles?auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYyMjM5MjYzOX0.FOwHgSr1K8ziv3bTksl0oJOU0vH0ELl6Tj52d2_6nfc

###
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "name": "marco",
    "email": "l@l",
    "pwd": "l"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "l@l",
    "pwd": "l"
}

###
GET http://localhost:3000/api/carts/last/users/4?auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTYyMjQ0NzgyMX0.wVTAULyG4rZfuzEuGeJQH16rIJjdm6R8cruLGrDx9Y0

###

POST http://localhost:3000/api/carts/1/articles?auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYyMjM5MjYzOX0.FOwHgSr1K8ziv3bTksl0oJOU0vH0ELl6Tj52d2_6nfc
Content-Type: application/json

{
    "artId": 1
}

### 
GET http://localhost:3000/api/carts/4/articles?auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTYyMjQ0NzgyMX0.wVTAULyG4rZfuzEuGeJQH16rIJjdm6R8cruLGrDx9Y0